# Generated by Django 5.0.7 on 2024-08-06 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to=settings.AUTH_USER_MODEL),
        ),
    ]
