# Generated by Django 5.0.7 on 2024-08-06 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_partida', models.CharField(max_length=8)),
                ('partida_privada', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('jugador_0', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugador_0', to=settings.AUTH_USER_MODEL)),
                ('jugador_ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugador_ganador', to=settings.AUTH_USER_MODEL)),
                ('jugador_x', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugador_x', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'db_table': 'Partida',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(default='', max_length=255)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partidas.partida')),
            ],
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_1', models.CharField(blank=True, default='', max_length=1)),
                ('pos_2', models.CharField(blank=True, default='', max_length=1)),
                ('pos_3', models.CharField(blank=True, default='', max_length=1)),
                ('pos_4', models.CharField(blank=True, default='', max_length=1)),
                ('pos_5', models.CharField(blank=True, default='', max_length=1)),
                ('pos_6', models.CharField(blank=True, default='', max_length=1)),
                ('pos_7', models.CharField(blank=True, default='', max_length=1)),
                ('pos_8', models.CharField(blank=True, default='', max_length=1)),
                ('pos_9', models.CharField(blank=True, default='', max_length=1)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablero', to='partidas.partida')),
            ],
            options={
                'verbose_name': 'Tablero',
                'verbose_name_plural': 'Tableros',
                'db_table': 'Tablero',
            },
        ),
    ]
